# Assignment 4: Data Wrangling
```
Course: ENV 700 - Environmental Data Exploration
Author: Student Name
Date: Fall 2026
```

This notebook accompanies the Python lessons on **Data Wrangling**, the second stage in the data analytics pipeline: **exploration, wrangling, analysis, and visualization**.

In this notebook, you will be working with US EPA Air Quality System (AQS) data on ozone and fine particulate matter (2.5 mm) levels recorded at its North Carolina monitoring stations for the years 2024 and 2025. The raw data files are provided as four separate CSV files: one for each pollutant-year combination. In this exercise, you will import each and wrangle them separately so that they can be combined into a single dataframe, where additional wrangling will enable comprehensive analysis of the dataset.

---
### 1. Set up your Python Session

#### ✅ 1.1 Import Packages
* Load the pathlib Path object and the Pandas package into your coding environnment

In [188]:
# 1.1 Import Packages
import pandas as pd
from pathlib import Path

#### ✅ 1.2 Set project folder variables
* Create three Path variables, one set to your project's **root folder** one set to the **raw data folder** and another to the **processed data folder**. 
* Display the the values of these three variables in your notebook.

In [189]:
# 1.2 Set project folders using relative paths
root_fldr = Path.cwd().parent
raw_fldr = root_fldr / "data" / "raw"
processed_fldr = root_fldr / "data" / "processed"

print(root_fldr)
print(raw_fldr)
print(processed_fldr)

c:\Users\sjh104\EDE 700\ENV700
c:\Users\sjh104\EDE 700\ENV700\data\raw
c:\Users\sjh104\EDE 700\ENV700\data\processed

#### ✅ 1.3 Set a path to the raw data files
* Create a Path variable pointing to the four EPA AQS files found in the raw data folder: 
    - `EPAair_O3_NC2024_raw.csv`
    - `EPAair_O3_NC2025_raw.csv`
    - `EPAair_PM25_NC2024_raw.csv`
    - `EPAair_PM25_NC2025_raw.csv`

In [190]:
# 1.3 Create file path variables
EPA_O3_2024_path = raw_fldr / "EPAair_O3_NC2024_raw.csv"
EPA_O3_2025_path = raw_fldr / "EPAair_O3_NC2025_raw.csv"
EPA_PM_2024_path = raw_fldr / "EPAair_PM25_NC2024_raw.csv"
EPA_PM_2025_path = raw_fldr / "EPAair_PM25_NC2025_raw.csv"

print(EPA_O3_2024_path, EPA_O3_2024_path.exists())
print(EPA_O3_2025_path, EPA_O3_2025_path.exists())
print(EPA_PM_2024_path, EPA_PM_2024_path.exists())
print(EPA_PM_2025_path, EPA_PM_2025_path.exists())

c:\Users\sjh104\EDE 700\ENV700\data\raw\EPAair_O3_NC2024_raw.csv True
c:\Users\sjh104\EDE 700\ENV700\data\raw\EPAair_O3_NC2025_raw.csv True
c:\Users\sjh104\EDE 700\ENV700\data\raw\EPAair_PM25_NC2024_raw.csv True
c:\Users\sjh104\EDE 700\ENV700\data\raw\EPAair_PM25_NC2025_raw.csv True

#### ✅ 1.4 Read the four files into separate dataframes
(*No need to set data types, parse dates, or perform any other specialize import functions here; we will wrangle value later.*)

In [191]:
# 1.4 Read data into dataframes
EPA_O3_2024 = pd.read_csv(EPA_O3_2024_path)
EPA_O3_2025 = pd.read_csv(EPA_O3_2025_path)
EPA_PM_2024 = pd.read_csv(EPA_PM_2024_path)
EPA_PM_2025 = pd.read_csv(EPA_PM_2025_path)

#EPA_O3_2024.head()
EPA_PM_2025.head()

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,Units,Daily AQI Value,Local Site Name,Daily Obs Count,Percent Complete,...,Method Code,Method Description,CBSA Code,CBSA Name,State FIPS Code,State,County FIPS Code,County,Site Latitude,Site Longitude
0,01/01/2025,AQS,370110002,1,0.7,ug/m3 LC,4,Linville Falls,1,100.0,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
1,01/04/2025,AQS,370110002,1,1.2,ug/m3 LC,7,Linville Falls,1,100.0,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
2,01/07/2025,AQS,370110002,1,1.5,ug/m3 LC,8,Linville Falls,1,100.0,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
3,01/10/2025,AQS,370110002,1,4.2,ug/m3 LC,23,Linville Falls,1,100.0,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072
4,01/13/2025,AQS,370110002,1,5.0,ug/m3 LC,28,Linville Falls,1,100.0,...,707.0,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,NaN,37,North Carolina,11,Avery,35.972347,-81.933072

#### ✅ 1.5 Report the dimensions of each dataframe
🔥***TIP***: *Each dataframe should have a different number of records.*

In [192]:
# 1.5 Report the dimensions of each dataset
print(EPA_O3_2024.shape)
print(EPA_O3_2025.shape)
print(EPA_PM_2024.shape)
print(EPA_PM_2025.shape)

(9519, 21)
(9466, 21)
(9752, 22)
(10184, 22)

---
### 2. Wrangle individual datasets

#### ✅ 2.1 Update data types
* Convert the `Date` column in each dataframe so that values are datetime objects. 
* List the date range for the two Ozone dataframes.

In [193]:
# Convert the Date column to DateTime objects
data = [EPA_O3_2024, EPA_O3_2025, EPA_PM_2024, EPA_PM_2025]

#loop through each data frame to convert date column
for df in data:
    df["Date"] = pd.to_datetime(df["Date"], format = '%m/%d/%Y')
    print(df["Date"].dtypes) # check date datatype

# Print date ranges
#01/01/2024 through 12/30/2024
print(f"\nOzone 2024: \n {EPA_O3_2024['Date'].describe()}")

#01/01/2025 through 12/31/2025
print(f"\nOzone 2025: \n {EPA_O3_2025['Date'].describe()}")

#alternative
print(f"\nThe date range for EPA Ozone 2024 is {EPA_O3_2024['Date'].min()} through {EPA_O3_2024['Date'].max()}")
print(f"The date range for EPA Ozone 2025 is {EPA_O3_2025['Date'].min()} through {EPA_O3_2025['Date'].max()}")

datetime64[us]
datetime64[us]
datetime64[us]
datetime64[us]

Ozone 2024:
 count                          9519
mean     2024-07-01 16:42:30.520012
min             2024-01-01 00:00:00
25%             2024-04-26 00:00:00
50%             2024-07-02 00:00:00
75%             2024-09-05 00:00:00
max             2024-12-30 00:00:00
Name: Date, dtype: object

Ozone 2025:
 count                          9466
mean     2025-07-03 01:43:35.761673
min             2025-01-01 00:00:00
25%             2025-04-27 00:00:00
50%             2025-07-04 00:00:00
75%             2025-09-08 00:00:00
max             2025-12-31 00:00:00
Name: Date, dtype: object

The date range for EPA Ozone 2024 is 2024-01-01 00:00:00 through 2024-12-30 00:00:00
The date range for EPA Ozone 2025 is 2025-01-01 00:00:00 through 2025-12-31 00:00:00

#### ✅ 2.2 Eliminate unnecessary columns
* Subset each dataframe to include only the following columns:  
```'Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude'```

In [227]:
# 2.2 Subset columns
#create var with core column names 
core_cols = ['Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude']

#create subsets
EPA_O3_2024_subset = EPA_O3_2024.loc[:,core_cols]
EPA_O3_2025_subset = EPA_O3_2025.loc[:,core_cols]
EPA_PM_2024_subset = EPA_PM_2024.loc[:,core_cols]
EPA_PM_2025_subset = EPA_PM_2025.loc[:,core_cols]

# = EPA_O3_2024.loc[:, core_cols]
EPA_O3_2025_subset.head()
#EPA_PM_2024_subset.head()

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
0,2025-03-01,47,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
1,2025-03-02,41,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
2,2025-03-03,43,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
3,2025-03-04,42,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191
4,2025-03-05,44,Taylorsville Liledoun,Ozone,Alexander,35.9138,-81.191

#### ✅ 2.3 Update values
* For the PM2.5 datasets, fill all cells in the `AQS Parameter Description` with the string "PM2.5".  
(*All cell values in this column will be identical.*)

In [195]:
# 2.3 Update values
EPA_PM_2024_subset['AQS Parameter Description'] = 'PM2.5'
EPA_PM_2025_subset['AQS Parameter Description'] = 'PM2.5'

---
### 3. Combine datasets

#### ✅ 3.1 Confirm dataframes are set to be merged
* Ensure that column names in each dataframe are indentical

In [196]:
# 3.1 Ensure column are same across all dataframes
print(EPA_PM_2024_subset.columns == EPA_PM_2025_subset.columns)
print(EPA_O3_2024_subset.columns == EPA_O3_2025_subset.columns)
print(EPA_PM_2024_subset.columns == EPA_O3_2024_subset.columns)

print(EPA_O3_2024_subset.columns)

[ True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True]
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')

#### ✅ 3.2 Combine the datasets 
* Combine the datasets using Pandas' `concat()` function
* Report the dimensions of the merged dataframe. (This should be `38,921 x 7`)

In [197]:
# 3.2 Concatentate & report shape
combined = pd.concat([EPA_O3_2024_subset, EPA_O3_2025_subset, EPA_PM_2024_subset, EPA_PM_2025_subset],
                     ignore_index=True)
print(combined.shape)

(38921, 7)

#### ✅ 3.3 Examine the contents of the merged dataframe
* Display a sample of 10 randomly selected rows, using the random state = 42

In [230]:
# 3.3 View a sample of data
combined.sample(10, random_state=42)

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
26921,2024-07-20,24,Pitt Agri. Center,PM2.5,Pitt,35.641276,-77.360126
6483,2024-04-22,40,University Meadows,Ozone,Mecklenburg,35.314158,-80.713469
34315,2025-02-18,53,Remount,PM2.5,Mecklenburg,35.213171,-80.874084
12494,2025-08-08,39,Clemmons Middle,Ozone,Forsyth,36.026612,-80.341962
27781,2024-01-08,12,Old High School,PM2.5,Swain,35.498711,-83.310242
23089,2024-08-26,59,Mendenhall School,PM2.5,Guilford,36.109006,-79.802314
35024,2025-02-16,27,Spruce Pine Hospital,PM2.5,Mitchell,35.912487,-82.062082
1157,2024-08-14,40,Beaufort,Ozone,Carteret,34.884800,-76.620300
4178,2024-09-14,31,Waynesville School,Ozone,Haywood,35.507224,-82.963625
13592,2025-03-29,45,Waynesville School,Ozone,Haywood,35.507224,-82.963625

---
### 4. Wrangle the combined dataset

#### ✅ 4.1 Subset rows 
* Generate a list of local site names common to all 4 dataframes (code provided, but replace the dataframe names to match your own).
* Create a subset of the full dataset, selecting those that match these local site names.
* Report the dimensions of the resulting dataframe. (This should be `18,778 x 7`)

In [199]:
# Generate a list of local site names common to all 4 dataframes
## Create set objects from the values in the Local Site Name columns
sites_oz24 = set(EPA_O3_2024_subset['Local Site Name']) #<-- update dataframe name to use your 2024 Ozone dataframe
sites_oz25 = set(EPA_O3_2025_subset['Local Site Name'])
sites_pm24 = set(EPA_PM_2024_subset['Local Site Name'])
sites_pm25 = set(EPA_PM_2025_subset['Local Site Name'])
## Compute the intersection 
common_sites = sites_oz24 & sites_oz25 & sites_pm24 & sites_pm25
common_sites

{'Bryson City',
 'Castle Hayne',
 'Clemmons Middle',
 'Durham Armory',
 'Frying Pan Mountain',
 'Garinger High School',
 'Hattie Avenue',
 'Leggett',
 'Linville Falls',
 'Mendenhall School',
 'Millbrook School',
 'Old High School',
 'Pitt Agri. Center',
 'Rockwell',
 'West Johnston Co.'}

In [223]:
# 4.1 Subset for records with sites in common
combined_subset = combined.loc[combined['Local Site Name'].isin(common_sites)]

combined_subset.shape

(18778, 7)

#### ✅ 4.2 Group and summarize data 
We want a dataset that lists one record per measured pollutant per location per day. To ensure we have that, we'll group data by date, local site name, AQS parameter, and county, computing the mean daily AQI value as well as mean latitude and longitude value. 
* Group the data on the grouping variables mentioned above. 
* For each group, compute mean daily AQI value, mean latitude, and mean longitude. 
* Reset the index of the summarized dataset to restore the product to a flat dataframe.
* Report the dimensions of the dataset. (This should be `17,017 x 7`.)

In [201]:
# 4.2 Group and summarize data, then report its dimensions
pollutant_summary = (
    combined_subset
    .groupby(['Date','Local Site Name', 'AQS Parameter Description', 'County'])
    .agg(
        mean_AQI = ("Daily AQI Value", "mean"),
        mean_lat = ("Site Latitude", "mean"),
        mean_long = ("Site Longitude", "mean")
    )
    .reset_index()
)

pollutant_summary.shape

(17017, 7)

#### ✅ 4.3 Add calculated columns
* Add `Year` and `Month` columns to your dataframe, deriving values from the `Date` field.

In [217]:
# 4.3 Calculate year and month columns
pollutant_summary["Year"] = pollutant_summary["Date"].dt.year
pollutant_summary["Month"] = pollutant_summary["Date"].dt.month

pollutant_summary.head()

#pollutant_summary.loc[(pollutant_summary['Local Site Name'] == 'Millbrook School') & (pollutant_summary['Date'] == '2024-01-01'),
 #                     ['Date','mean_AQI', 'AQS Parameter Description', 'Month', 'Year']]

,Date,Local Site Name,AQS Parameter Description,County,mean_AQI,mean_lat,mean_long,Year,Month
0,2024-01-01,Bryson City,PM2.5,Swain,43.0,35.434767,-83.442133,2024,1
1,2024-01-01,Castle Hayne,PM2.5,New Hanover,44.5,34.364167,-77.838611,2024,1
2,2024-01-01,Clemmons Middle,PM2.5,Forsyth,47.5,36.026612,-80.341962,2024,1
3,2024-01-01,Durham Armory,PM2.5,Durham,61.0,36.032955,-78.904037,2024,1
4,2024-01-01,Frying Pan Mountain,PM2.5,Haywood,14.0,35.379167,-82.792500,2024,1

#### ✅ 4.4 Spread AQI values into separate columns: OZone & PM2.5
* Reshape our table so that Daily AQI values for Ozone and PM2.5 data appear in separate columns.
* Reset the index of the reshaped table to restore it as a flat dataframe.
* Display the first 5 records in the resulting dataframe

In [226]:
# 4.4 Spread data so Ozone, PM2.5 daily AQI valiues occupy separate columns
pollutant_summary_wide = (
    pollutant_summary
    .pivot_table(
        index=['Date', 'Local Site Name', 'County','mean_lat', 'mean_long', 'Year', 'Month'],
        columns='AQS Parameter Description',
        values='mean_AQI'
    )
    .reset_index()
)

pollutant_summary_wide.head()
#pollutant_summary_wide.sample(10,random_state=42)

AQS Parameter Description,Date,Local Site Name,County,mean_lat,mean_long,Year,Month,Ozone,PM2.5
0,2024-01-01,Bryson City,Swain,35.434767,-83.442133,2024,1,NaN,43.0
1,2024-01-01,Castle Hayne,New Hanover,34.364167,-77.838611,2024,1,NaN,44.5
2,2024-01-01,Clemmons Middle,Forsyth,36.026612,-80.341962,2024,1,NaN,47.5
3,2024-01-01,Durham Armory,Durham,36.032955,-78.904037,2024,1,NaN,61.0
4,2024-01-01,Frying Pan Mountain,Haywood,35.379167,-82.792500,2024,1,NaN,14.0

---
## 5. Save your processed dataset

#### ✅ 5.1 Save the spread dataset to a file 
* Name the spread data file `EPAair_O3_PM25_NC2425_Processed.csv`
* Save it to your processed data folder
* Do not include the dataframe index in your saved file

In [204]:
# 5.1 Save the file
pollutant_summary_wide.to_csv(processed_fldr/'EPAair_O3_PM25_NC2425_Processed.csv', index = False)

---
## 6. Summarize and explore the data

#### ✅ 6.1 Generate a month summary table
* Group the above table to compute mean Ozone and PM2.5 values for each unique site, month, year combination. Be sure to reset the index of the product. 
* Display the first 5 records of this table.

In [219]:
# 6.1 Generate a summary table and show its first 5 records
monthly_summary = (
    pollutant_summary_wide
    .groupby(['Local Site Name', 'Year', 'Month'])
    .agg(
        mean_O3 = ("Ozone", "mean"),
        mean_PM = ("PM2.5", "mean")
    )
    .reset_index()
)

monthly_summary.head()

  Local Site Name  Year  Month    mean_O3    mean_PM
0     Bryson City  2024      1        NaN  22.580645
1     Bryson City  2024      2        NaN  32.000000
2     Bryson City  2024      3  40.709677  30.935484
3     Bryson City  2024      4  43.793103  36.066667
4     Bryson City  2024      5  37.419355  30.387097

In [205]:
# 6.1 Generate a summary table and show its first 5 records
monthly_summary = (
    pollutant_summary_wide
    .groupby(['Local Site Name', 'Month', 'Year'])
    .agg(
        mean_O3 = ("Ozone", "mean"),
        mean_PM = ("PM2.5", "mean")
    )
    .reset_index()
)

monthly_summary.head()

  Local Site Name  Month  Year    mean_O3    mean_PM
0     Bryson City      1  2024        NaN  22.580645
1     Bryson City      1  2025        NaN  25.838710
2     Bryson City      2  2024        NaN  32.000000
3     Bryson City      2  2025        NaN  32.678571
4     Bryson City      3  2024  40.709677  30.935484

---
## 7. Submission
- Save, stage, and commit this notebook
- Push changes to your GitHub account
- Export as an HTML document
- Submit both your `.ipynb` and `.html` document to Canvas.